apiVersion: v1
kind: Secret
metadata:
  name: hospital-app-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017/hospital_management"
  SESSION_SECRET: "h0sp1tal_s3ss10n_s3cr3t_key_2026"
  JWT_SECRET: "h0sp1tal_jwt_auth_s3cr3t_key_2026"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin123"