{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
{{- end }}
